theme: jekyll-theme-cayman
title: Communacademy App Demo
description: Communacademy is an iOS app facilitating tech-based communication for students with speech or linguistic barriers. The developers unfortunately had to take this app off the App Store due to funding issues, but scroll down to see our demo!
github:
  is_project_page: false
